package fr.boitakub.bogadex.common.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF705D00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE16F)
val md_theme_light_onPrimaryContainer = Color(0xFF221B00)
val md_theme_light_secondary = Color(0xFF006B5F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF75F8E3)
val md_theme_light_onSecondaryContainer = Color(0xFF00201C)
val md_theme_light_tertiary = Color(0xFF705D00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFE16F)
val md_theme_light_onTertiaryContainer = Color(0xFF221B00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFFDC)
val md_theme_light_onBackground = Color(0xFF191E00)
val md_theme_light_surface = Color(0xFFFCFFDC)
val md_theme_light_onSurface = Color(0xFF191E00)
val md_theme_light_surfaceVariant = Color(0xFFEAE2CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4B4639)
val md_theme_light_outline = Color(0xFF7C7767)
val md_theme_light_inverseOnSurface = Color(0xFFE9FA86)
val md_theme_light_inverseSurface = Color(0xFF2D3400)
val md_theme_light_inversePrimary = Color(0xFFE3C54A)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF705D00)
val md_theme_light_outlineVariant = Color(0xFFCDC6B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFE3C54A)
val md_theme_dark_onPrimary = Color(0xFF3A3000)
val md_theme_dark_primaryContainer = Color(0xFF544600)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE16F)
val md_theme_dark_secondary = Color(0xFF55DBC7)
val md_theme_dark_onSecondary = Color(0xFF003731)
val md_theme_dark_secondaryContainer = Color(0xFF005047)
val md_theme_dark_onSecondaryContainer = Color(0xFF75F8E3)
val md_theme_dark_tertiary = Color(0xFFE3C54A)
val md_theme_dark_onTertiary = Color(0xFF3A3000)
val md_theme_dark_tertiaryContainer = Color(0xFF544600)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE16F)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191E00)
val md_theme_dark_onBackground = Color(0xFFDBEC79)
val md_theme_dark_surface = Color(0xFF191E00)
val md_theme_dark_onSurface = Color(0xFFDBEC79)
val md_theme_dark_surfaceVariant = Color(0xFF4B4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCDC6B4)
val md_theme_dark_outline = Color(0xFF979080)
val md_theme_dark_inverseOnSurface = Color(0xFF191E00)
val md_theme_dark_inverseSurface = Color(0xFFDBEC79)
val md_theme_dark_inversePrimary = Color(0xFF705D00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFE3C54A)
val md_theme_dark_outlineVariant = Color(0xFF4B4639)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF705D00)
